#include "book_management.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "utility.h"

void removeNewLine(char* string) {

    size_t length = strlen(string);

    if((length > 0) && (string[length-1] == '\n')) {
        string[length-1] ='\0';
    }
    return;
}
int optionChoice( void ) {
    int option = -1;
    char line[80];

    // read in the current line as a string
    fgets(line,80,stdin);

    // atoi() converts string to integer, returns 0 if could not convert
    option = (int)atoi(line);

    return option;
}
void first_book_get(BookList *p){
    //最长值初始化
    p->authors_longest=0;
    p->title_longest=0;
    p->length=1;
    //头节点虚拟初始化
    p->list->id=10000;
    
    p->list->title=(char*)malloc(sizeof(char)*80);
    p->list->title="xuni";
    //strcpy(p->title,book.title);
    
    p->list->authors=(char*)malloc(sizeof(char)*80);
    p->list->authors="xuni";
    //strcpy(p->authors,book.authors);

    p->list->next=NULL;
    
    p->list->year=0000;
    p->list->copies=0;
}

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file,BookList *all_book){
    Book *last;
    last=all_book->list->next;
    
    while(last){

        fprintf(file,"%d-%s-%s-%d-%d\n", last->id,last->title,last->authors,last->year,last->copies);
        last=last->next;
    }
    return 0;
}

int store_users(FILE *file,UserList *all_user){
    User *last;
    last=all_user->list->next;

    while(last){
        fprintf(file,"%s-%s\n", last->username,last->password);
        last=last->next;
    }
    return 0;
}

int store_loans(FILE *file,UserList *all_user){
    User *last;
    last=all_user->list->next;

    while(last){
        fprintf(file,"%s", last->username);
        Book *p;
        p=last->loans->list->next;
        while(p){
            fprintf(file,"-%d", p->id);
            p=p->next;
        }
        fprintf(file,"\n");
        last=last->next;
    }
    return 0;
}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file, BookList *all_book){

    if(file == NULL||all_book == NULL){
        return -2;
    }

    int x=1;
    Book *first,*last;
    CreateNode(first);     /* 建立附加头结点 */
    all_book->list = first;
    first_book_get(all_book);
    
    last=first;          /* last始终指向当前最后一个结点 */
    //最长值初始化
    all_book->authors_longest=0;
    all_book->title_longest=0;
    
    char line[100];
    while((fgets(line,100,file)) != NULL)
    { 
        //removeNewLine(line);
        Book *p;

        CreateNode(p);
        //const char s[2] = "-";
        char* fenduan;
        fenduan=strtok(line, "-");
        p->id=(int)atoi(fenduan);

        fenduan=strtok(NULL, "-");
        p->title=(char*)malloc(sizeof(char)*80);
        // printf("%s\n",fenduan);
        strcpy(p->title,fenduan);
        int l_title=strlen(p->title);
        if(l_title>all_book->title_longest) all_book->title_longest=l_title;

        fenduan=strtok(NULL, "-");
        p->authors=(char*)malloc(sizeof(char)*80);
        //printf("%s\n",fenduan);
        strcpy(p->authors,fenduan);
        int l_authors=strlen(p->authors);
        if(l_authors>all_book->authors_longest) all_book->authors_longest=l_authors;

        fenduan=strtok(NULL, "-");
        p->year=(int)atoi(fenduan);
        
        fenduan=strtok(NULL, "-");
        p->copies=(int)atoi(fenduan);
        //test
        //printf("%d\t%s\t\t%s\t%d\t%d\n",p->id,p->title,p->authors,p->year,p->copies);
        /*新结点插入到链表结尾*/
        last->next=p;last=p; 
        x++;        
    }
    /*最后一个结点指针域赋值为NULL*/
    last->next=NULL;        
    all_book->length=x;
    //BookList *k;
    //k=(BookList*)malloc(sizeof(BookList));
    //k->list=first;
    //k->length=x;
    return 0;

}

//load users to list
int load_users(FILE *file, UserList *all_user)
{
    if(file==NULL||all_user==NULL){
        return -2;
    }
    int x=1;
    User *first,*last;
    /* 建立附加头结点 */
    first=(User*)malloc(sizeof(User));
    all_user->list = first;

    //头节点虚拟初始化
    first->username="xuni";
    first->password="xuni";
    first->loans=NULL;

    
    last=first;          /* last始终指向当前最后一个结点 */
    char line[100];
    while((fgets(line,100,file)) != NULL)
    { 
        removeNewLine(line);
        User *p;
        p=(User*)malloc(sizeof(User));
        //const char s[2] = "-";
        char* fenduan;
        fenduan=strtok(line, "-");
        p->username=(char*)malloc(sizeof(char)*80);
        // printf("%s\n",fenduan);
        strcpy(p->username,fenduan);
        
        fenduan=strtok(NULL, "-");
        p->password=(char*)malloc(sizeof(char)*80);
        //printf("%s\n",fenduan);
        strcpy(p->password,fenduan);

        p->loans=(BookList*)malloc(sizeof(BookList));
        p->loans->list=(Book*)malloc(sizeof(Book));
        first_book_get(p->loans);
        
        //printf("%s\t\t%s\n",p->username,p->password);
        
        /*新结点插入到链表结尾*/
        last->next=p;last=p; 
        x++;        
    }
    /*最后一个结点指针域赋值为NULL*/
    last->next=NULL;        
    all_user->length=x;
    //BookList *k;
    //k=(BookList*)malloc(sizeof(BookList));
    //k->list=first;
    //k->length=x;
    return 0;
}

int load_loans(FILE *file, UserList *all_user,BookList *all_book){
    if(file==NULL||all_user==NULL){
        return -2;
    }
    
    char line[100];
    while((fgets(line,100,file)) != NULL)
    { 
        removeNewLine(line);
        User *p=all_user->list->next;
        
        char* fenduan;
        fenduan=strtok(line, "-");
        
        //找到对应的user指针
        while(p){
            if(!strcmp(p->username,fenduan)){
                break;
            }
            p=p->next;
        }
        
        //实现添加,巧妙的数据结构
        while( fenduan != NULL ) {
            
            fenduan = strtok(NULL, "-");
            if(fenduan == NULL)break;
            int id=(int)atoi(fenduan);
            add_loans(id,2,p,all_book);
        }
      
    }
    
    return 0;
}

int add_loans(int id, int option,User* user,BookList *all_book){
    Book *last;
    last=all_book->list->next;
    
    while(last){
        if(last->id==id)
            break;
        last=last->next;
    }

    if(option==1){
        
        last->copies--;
    }
    
    add_book(*last,user->loans);
    user->loans->length++;
    return 0;
}

int remove_loans(int id, User* user,BookList *all_book){
    Book *p,*last;
    last=user->loans->list->next;
    p=all_book->list->next;
    while(last->id==id){
        last=last->next;
    }
    while(p){
        if(p->id==id){
            p->copies++;
            break;
        }
        p=p->next;
    }
    remove_book(*last,user->loans);
    user->loans->length--;
    return 0;
}

int remove_loansBy_libraian(int id, UserList* all_user,BookList *all_book){
    User *p;
    p=all_user->list->next;
    while(p){
        remove_loans(id,p,all_book);
    }
    return 0;
}

int add_user(User user,UserList *all_user){

    User *p,*last;
    last=all_user->list;
    p=(User*)malloc(sizeof(User));

    p->username=(char*)malloc(sizeof(char)*80);
    strcpy(p->username,user.username);

    p->password=(char*)malloc(sizeof(char)*80);
    strcpy(p->password,user.password);

    p->loans=(BookList*)malloc(sizeof(BookList));
    p->loans->list=(Book*)malloc(sizeof(Book));
    first_book_get(p->loans);

    while(last->next){
        last=last->next;
    }
    last->next=p;
    p->next=NULL;
    all_user->length++;

    return 0;
}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book,BookList *all_book){

    Book *p,*last;
    last=all_book->list;
    CreateNode(p);
    p->id=book.id;
    
    p->title=(char*)malloc(sizeof(char)*80);
    strcpy(p->title,book.title);
    int l_title=strlen(p->title);
    if(l_title>all_book->title_longest) all_book->title_longest=l_title;
    
    p->authors=(char*)malloc(sizeof(char)*80);
    strcpy(p->authors,book.authors);
    int l_authors=strlen(p->authors);
    if(l_authors>all_book->authors_longest) all_book->authors_longest=l_authors;

    p->year=book.year;
    p->copies=book.copies;

    while(last->next){
        last=last->next;
    }

    last->next=p;
    p->next=NULL;
    all_book->length++;

    return 0;

}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book,BookList *all_book){
    //if (!all_book)
		//load_books(all_book);
    Book *p=all_book->list;
    int judge=1;
    while(p){
        if (book.id==p->next->id)
        {
            free(p->next->title);
            free(p->next->authors);
            Book *h=p->next;
            p->next=p->next->next;
            DeleteNode(h);
            all_book->length--;
            judge=0;
            break;
        }
        p=p->next;
    }
    if(judge==0)return 0;
    else return 1;
}

void delete_book(BookList *all_book){
    Book *p=all_book->list,*q;
    while(p->next)       /* p没有指向链表尾则循环 */
    {   
        //free(p->title);
        //free(p->authors);
        q=p;                        /* 保存p */ 
        p=p->next;           /* p向前推进一个结点 */
        //free((void *)q);
        DeleteNode(q);             /* 删除结点*q */
    }
    DeleteNode(p);
    return ;
}

//finds books with a given title.
//returns a BookList structure, where the field "list" is a list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_title (const char *title,BookList *all_book){
    //if (!all_book)
		//load_books(all_book);
    Book *p=all_book->list->next;
    BookList *find_book = (BookList *)malloc( sizeof(BookList) );

    
    Book *first;
    CreateNode(first);     /* 建立附加头结点 */
    find_book->list = first;
    first_book_get(find_book);

    while(p){
        if (!strcmp(p->title,title))
        {
            add_book(*p,find_book);
        }
        p=p->next;
    }

	return *find_book;
}

//finds books with the given authors.
//returns a Booklist structure, where the field "list" is a newly allocated list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_author (const char *author,BookList *all_book){
    //if (!all_book)
		//load_books(all_book);
    Book *p=all_book->list->next;
    BookList *find_book = (BookList *)malloc( sizeof(BookList) );

    
    Book *first;
    CreateNode(first);     /* 建立附加头结点 */
    find_book->list = first;
    first_book_get(find_book);
    
    while(p){
        if (!strcmp(p->authors,author))
        {
            add_book(*p,find_book);
        }
        p=p->next;
    }

	return *find_book;

}

//finds books published in the given year.
//returns a Booklist structure, where the field "list" is a list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_year (unsigned int year,BookList *all_book){
    //if (!all_book)
		//load_books(all_book);
    Book *p=all_book->list->next;
    BookList *find_book = (BookList *)malloc( sizeof(BookList) );

    
    Book *first;
    CreateNode(first);     /* 建立附加头结点 */
    find_book->list = first;
    first_book_get(find_book);
    
    while(p){
        if (p->year==year)
        {
            add_book(*p,find_book);
        }
        p=p->next;
    }

	return *find_book;

}

//******************************************************
void printbook(BookList h)     
{   
    
    Book *p=h.list->next;

    if(p==NULL){
        printf("There have no book here!\n");
        return;
    }
    int interval=7;  
    /*p指向第一个数据结点, 如果链表不带附加头结点则p=h;*/
    //打印表头
    //printf("ID\tTitle\tAuthor\tyear\tcopies\n");
    printf("ID");
    for(int i=1;i<=interval;i++)printf(" ");
    printf("Title");
    for(int i=1;i<=h.title_longest+interval-5;i++)printf(" ");
    printf("Author");
    for(int i=1;i<=h.authors_longest+interval-6;i++)printf(" ");
    printf("year");
    for(int i=1;i<=interval;i++)printf(" ");
    printf("copies\n");

    while(p) 
    { 
        
        int tl=strlen(p->title);
        int al=strlen(p->authors);
        
        //printf("%d\t%s\t%s\t%d\t%d\n",p->id,p->title,p->authors,p->year,p->copies);
        printf("%d",p->id);//这里只考虑了id小于10--
        for(int i=1;i<=interval+1;i++)printf(" ");
        printf("%s",p->title);
        for(int i=1;i<=h.title_longest+interval-tl;i++)printf(" ");
        printf("%s",p->authors);
        for(int i=1;i<=h.authors_longest+interval-al;i++)printf(" ");
        printf("%d",p->year);
        for(int i=1;i<=interval;i++)printf(" ");
        printf("%d\n",p->copies);

        p=p->next; 
    }
    return;
}

void reg(UserList* ul)
{
    User login_user;
    char name[80],password[80];
    printf("Please enter a username: ");
    fgets(name,80,stdin);
    removeNewLine(name);
    printf("Please enter a password: ");
    fgets(password,80,stdin);
    removeNewLine(password);
    int judge=1;
    User *p=ul->list->next;
    //find if the name is avaible
    
    while(p)
    {
        if(!strcmp(p->username,name))
        {
            judge=0;
            break;
        }
        
        p=p->next;
        
    }
    if(judge==0||(!strcmp(name,"librarian")))
    {
        printf("Sorry, registration unsuccessful, the username you entered already exists.\n");
    }
    else if( (!strcmp(name,""))||(!strcmp(password,"")))
    { 
        printf("Sorry, registration unsuccessful, the username or password can't be blank.\n");
    }
    else if(judge==1)
    {
        //导入近user.txt或者先放入用户链表中。
        printf("add\n");
        login_user.username=(char*)malloc(sizeof(char)*80);
        // printf("%s\n",fenduan);
        strcpy(login_user.username,name);
        
        login_user.password=(char*)malloc(sizeof(char)*80);
        //printf("%s\n",fenduan);
        strcpy(login_user.password,password);
        login_user.loans=NULL;
        login_user.next=NULL;   
        int success=add_user(login_user,ul);
        if(success==0)
            printf("\nregister success!\n");
    }
    return;
}

User* login(UserList* ul)
{
    char name[80],input_password[80];
    printf("Please enter your username: ");
    fgets(name,80,stdin);
    removeNewLine(name);
    printf("Please enter your password: ");
    fgets(input_password,80,stdin);
    removeNewLine(input_password);
    //printf("input success\n");
    int judge=0;
    User *p=ul->list->next;
    //find if the user is exist
    while(p)
    {
        printf("%s\t%s\n",p->username,p->password);
        printf("%d %d\n",(!strcmp(p->username,name)),(!strcmp(p->password,input_password)));
        printf("%s\t%s\n",p->username,p->password);
        if((!strcmp(p->username,name))&&(!strcmp(p->password,input_password)))
        {
            
               judge=1; 
               
               break;
             
        }
        
        p=p->next;
        
    }
    if((!strcmp(name,"librarian"))&&(!strcmp(input_password,"librarian")))
    {   
        judge=2;
    }
    if(judge==0)
    {
        printf("Sorry, login unsuccessful, the username and password you entered are not exists.\n");
        return NULL;
    }
    else if(judge==2)
    {
        User* admin;
        admin=malloc(sizeof(User));
        admin->username="librarian";
        admin->password="librarian";
        admin->next=NULL;
        admin->loans=NULL;
        return admin;
    }
    else if(judge==1)
    {
        
        return p;
    }
    

}

void SearchBook( BookList *all_book )//--
{
    int SearchIn=1;
    int option;

    printf("\nLoading search menu...\n");
    while( SearchIn ){  
        printf("Please choose an option:\n");
        printf("1) Find book by title\n2) Find book by author\n3) Find book by year\n4) Return to previous menu\n Option: ");
        option = optionChoice();

        if( option == 1 ) {//按名字搜--
            char title[80];
            printf("Please enter the title:");
            fgets(title,80,stdin);
            removeNewLine(title);
            BookList k=find_book_by_title (title,all_book);
            printbook(k);
        }
        else if( option == 2 ) {//按作者--
            char author[80];
            printf("Please enter the author:");
            fgets(author,80,stdin);
            removeNewLine(author);
            BookList k=find_book_by_author (author,all_book);
            printbook(k);
            
        }
        else if( option == 3 ) {//按年--
            int year;
            printf("Please enter the author:");
            year = optionChoice();
            if(year==0)
               printf("Sorry,the year you entered was invalid, please try again.\n");
            else 
            {
               BookList k=find_book_by_year (year,all_book);
               printbook(k);
            }
        }
        else if( option == 4 ) {//退出--
            SearchIn = 0;
            printf("\nReturning to previous menu...\n");
        }
        else
            printf("\nSorry,the option you entered was invalid, please try again.\n");
      }
}

int input_add_loan(User* user,BookList*all_book){
    int l_id;
    printf("Enter the id of the book you wish to loan: \n");
    l_id=optionChoice();
    if(l_id==0){
    printf("Sorry,the id you entered was invalid, please try again.\n");
    return 0;}
    Book* k=all_book->list->next;
    int h_i=0;
    while(k)
    {
        if(k->id==l_id){
            h_i=1;
            break;
        }
        k=k->next;
    }
    if(h_i==0){
        printf("Sorry, the id you enterd don't exsist.\n");
        return 0;
    }
    Book* p=user->loans->list->next;
    while(p)
    {
        if(p->id==l_id){
            printf("Sorry,you already have a copy of this book on loan");
            return 0;
        }
        p=p->next;

    }
    return l_id;
}

int input_remove_loan(User* user,BookList*all_book){
    int l_id;
    printf("Below the list of book you are currently borrowing: \n");
    printbook(*(user->loans));

    printf("Enter the ID number of the book you wish to return: \n");
    l_id=optionChoice();
    if(l_id==0){
    printf("Sorry,the id you entered was invalid, please try again.\n");
    return 0;}
    Book* k=user->loans->list->next;
    int h_i=0;
    while(k)
    {
        if(k->id==l_id){
            h_i=1;
            break;
        }
        k=k->next;
    }
    if(h_i==0){
        printf("Sorry,you don't have the copy of this book!\n");
        return 0;
    }
    if(k->copies==0){
        printf("Sorry,the copy of this book is none!\n");
        return 0;
    }
    return l_id;
}

Book input_remove_book(BookList *all_book){
    Book remove;

    printf("Enter the id of the book you wish to remove: \n");
    remove.id = optionChoice();
    if(remove.id==0)printf("Sorry,the id you entered was invalid, please try again.\n");
    remove.title="meiyong";
    remove.authors="meiyong";
    remove.year=1;
    remove.copies=1;
    remove.next=NULL;

    return remove;

}

Book input_add_book(BookList *all_book){

    Book input;

    input.title=(char*)malloc(sizeof(char)*80);
    printf("Enter the title of the book you wish to add: ");
    fgets(input.title,80,stdin);
    removeNewLine(input.title);
    if(!strcmp(input.title,""))
    printf("Sorry,the title can't be empty, please try again.\n");
    
    input.authors=(char*)malloc(sizeof(char)*80);
    printf("Enter the author of the book you wish to add: ");
    fgets(input.authors,80,stdin);
    removeNewLine(input.authors);
    if(!strcmp(input.authors,""))
    printf("Sorry,the author can't be empty, please try again.\n");

    printf("Enter the year of the book you wish to add was released: ");
    input.year = optionChoice();
    if(input.year==0)printf("Sorry,the year you entered was invalid, please try again.\n");
    
    printf("Enter the number of copies of the book that you wish to add: ");
    input.copies = optionChoice();

    input.next=NULL;

    Book *last;
    last=all_book->list;
    while(last->next){
        last=last->next;
    }
    input.id=last->id+1;//有问题，关于id

    return input;
}
void userCLI( User* user, BookList *all_book ) {
    int userLoggedIn = 1;
    int option;

    while( userLoggedIn ){
        printf("\n(logged in as: %s)\n",user->username);
        printf("Please choose an option:\n");
        printf("1) Borrow a book\n2) Return a book\n3) Search for book\n4) Display all books\n5) Log out\n Option: ");
        option = optionChoice();

        if( option == 1 ) {//借书
            int L=input_add_loan(user, all_book);
            if( L != 0 ){
                int success=add_loans(L, 1, user, all_book);
                if( success == 0)   
                    printf("Book was successfully loaned!\n");
            }
    
        }
        else if( option == 2 ) {//还书
            int L=input_remove_loan(user, all_book);
            if( L != 0 ){
                int success=remove_loans(L, user, all_book);
                if( success == 0)   
                    printf("Returned book successfully!\n");
            }
        }
        else if( option == 3 ) {//查找书--
            SearchBook( all_book );
            
        }
        else if( option == 4 ) {//展示书--
            printbook(*all_book);
        }
        else if( option == 5 ) {
            userLoggedIn = 0;
            printf("\nLogging out...\n");
        }
        else
            printf("\nUnknown option\n");
    }
    return;
}

// Menu system for the librarian

void librarianCLI( BookList *all_book, UserList *all_user) {
    int librarianLoggedIn = 1;
    int option;

    while( librarianLoggedIn ){
        printf("\n(logged in as: librarian)\n");
        printf("Please choose an option:\n");
        printf("1) Add a book\n2) Remove a book\n3) Search for book\n4) Display all books\n5) Log out\n Option: ");
        option = optionChoice();

        if( option == 1 ) {
            //tianjiashu,--
            int success=add_book((input_add_book(all_book)),all_book);
            if( success == 0)   
            printf("Book was successfully added!\n"); 
        }
        else if( option == 2 ) {//移除书--
            Book p=input_remove_book(all_book);
            int success=remove_book(p,all_book);
            remove_loansBy_libraian(p.id, all_user,all_book);
            if( success == 0)   
            printf("Book was successfully removed!\n");
            
        }
        else if( option == 3 ) {//查找书--
            
            SearchBook( all_book );
        }
        else if( option == 4 ) {//展示书--
            printbook(*all_book);
        }
        else if( option == 5 ) {
            librarianLoggedIn = 0;
            printf("\nLogging out...\n");
        }
        else
            printf("\nSorry,the option you entered was invalid, please try again.\n");
    }
    return;
}
void initLibrary( BookList *all_book, UserList *all_user){

  char* bookFile="book.txt";
  FILE *fp = NULL;
  fp = fopen(bookFile, "r");
  int bookFile_error=load_books(fp, all_book);
  fclose(fp);
  if(bookFile_error==-2)
  printf("Error loading book file\n");
  
  char* userFile="user.txt";
  fp = NULL;
  fp = fopen(userFile, "r");
  int userFile_error=load_users(fp, all_user);
  fclose(fp);
  if(userFile_error==-2)
  printf("Error loading user file\n");
  
  char* loanFile="loans.txt";
  fp = NULL;
  fp = fopen(loanFile, "r");
  
  int loanFile_error=load_loans(fp, all_user, all_book);
  
  fclose(fp);
  if(loanFile_error==-2)
  printf("Error loading loan file\n");
  //printf("Error\nBook file does not exist: %s\n",bookFile);
  //exit(0);
  
  return;
}


// Free any allocated library data
// Input: 
// theLibrary - library data structure

void exitLibrary( BookList *all_book, UserList *all_user) {

    char* bookFile="book.txt";
    FILE *fp = NULL;
    fp = fopen(bookFile, "w+");
    int bookFile_error=store_books(fp,all_book);
    fclose(fp);
    if(bookFile_error==-2)
    printf("Error store book file");
    
    char* userFile="user.txt";
    fp = NULL;
    fp = fopen(userFile, "w+");
    int userFile_error=store_users(fp,all_user);
    fclose(fp);
    if(userFile_error==-2)
    printf("Error store book file");

    char* loanFile="loans.txt";
    fp = NULL;
    fp = fopen(loanFile, "w+");
    int loanFile_error=store_loans(fp, all_user);
    fclose(fp);
    if(loanFile_error==-2)
    printf("Error store book file");
    
    
    // free the allocated lists
    delete_book(all_book);
    
    User *p=all_user->list,*q;
    while(p)       /* p没有指向链表尾则循环 */
    {   
        //free(p->username);
        //free(p->password);
        delete_book(p->loans);
        free((void *)p->loans);
        q=p;                        /* 保存p */ 
        p=p->next;           /* p向前推进一个结点 */
        DeleteNode(q);             /* 删除结点*q */
    }
    return;
}

// DO NOT ALTER THIS FUNCTION
// Library menu system

void libraryCLI(){
    int libraryOpen = 1;
    int option;
    
    // create the library structure 
    BookList *all_book = (BookList *)malloc( sizeof(BookList) );
    UserList *all_user = (UserList *)malloc( sizeof(UserList) );
    
    initLibrary( all_book, all_user );

    printbook(*all_book);
    User *p=all_user->list->next;
    User *k=all_user->list->next;
    while(p){
        printf("%s\t%s\n",p->username,p->password);
        p=p->next;
    }
    while(k){
        printf("%s\n",k->username);
        printbook(*(k->loans));
        k=k->next;
    }
    
    while( libraryOpen ){
        printf("\nPlease choose an option\n1) Register\n2) login\n3) Search for book\n4) Display all book\n5) Quit\n Option:");
        option = optionChoice();

        if( option == 1 ) {
            reg( all_user );//user list设置
        }
        else if( option == 2 ) {
            User* k=login( all_user );//user list还未设置
            if(k!=NULL)
            {
                if(!strcmp(k->username,"librarian")&&!strcmp(k->password,"librarian"))
                    librarianCLI(all_book, all_user);
                else userCLI( k, all_book );
            }
      
        }
        else if( option == 3 ) {
            //search for book
            SearchBook( all_book );
        }
        else if( option == 4 ) {
            //zhanshiliebiaohanshu
            printbook(*all_book);
        }
        else if( option == 5 ) {
            libraryOpen = 0;
            printf("\nThank you for using the library!\nGoodbye!\n");
        }
        else
            printf("\nSorry,the option you entered was invalid, please try again.\n");
    }
    
    // free the library structure
    exitLibrary( all_book, all_user);
    free( all_book );
    free( all_user );
    return;
}

int main( int argc, char **argv )
{
    //char bookFile[40];

    //TO DO :
    /*
    if( argc != 2 )
    {
        // check that correct number of command line arguments are entered    
        // use the error message 
        printf("Error\nExpected use: ./library books.txt\n"); 
        // exit the application if there is an error
        return 0;
    }
    // assign command line value to filename string
    strcpy(&bookFile[0],argv[1]);
    */
    //printf("%s\n",bookFile);                 test

    // DO NOT ALTER
    // start the system
    printf("\nIntialising library system!\n");
    libraryCLI();
    printf("\nClosing library system!\n\n");

    return 0;
}
