
#include "book_management.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>



//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file){
    

}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file, BookList *all_book){

    int x=1;
    Book *first=all_book->list,*p,*last;
    CreateNode(first);     /* 建立附加头结点 */
    last=first;          /* last始终指向当前最后一个结点 */
    printf("5\n");
    
    char* l_title=(char*)malloc(sizeof(char)*80);
    char* l_authors=(char*)malloc(sizeof(char)*80);
    unsigned int l_id,l_year,l_copies;

    while((fscanf(file, "%u\t%s\t%s\t%u\t%u\n", l_id,l_title, l_authors,l_year,l_copies)) != EOF)
    { 
        
        //if (feof(file)) break;
        CreateNode(p);
        p->id=l_id;
        p->title=l_title;
        p->authors=l_authors;
        p->year=l_year;
        p->copies=l_copies;
        printf("7\n");
        
           /* 建立一个新结点 */
        last->next=p;last=p; /*新结点插入到链表结尾*/
        x++;        
    }
    printf("6");
    last->next=NULL;        /*最后一个结点指针域赋值为NULL*/
    //BookList *k;
    //k=(BookList*)malloc(sizeof(BookList));
    //k->list=first;
    //k->length=x;
    return 0;

}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book){

}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book){

}

//finds books with a given title.
//returns a BookList structure, where the field "list" is a list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_title (const char *title){

}

//finds books with the given authors.
//returns a Booklist structure, where the field "list" is a newly allocated list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_author (const char *author){

}

//finds books published in the given year.
//returns a Booklist structure, where the field "list" is a list of books, or null if no book with the 
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_year (unsigned int year){

}

//******************************************************
void printbook(BookList h)     /* h为头指针 */
{   
    
    Book *p=h.list->next;
    int interval=7;  
    /*p指向第一个数据结点, 如果链表不带附加头结点则p=h;*/
    //打印表头
    printf("ID");
    for(int i=1;i<=interval;i++)printf(" ");
    printf("Title");
    for(int i=1;i<=h.title_longest+interval-5;i++)printf(" ");
    printf("Author");
    for(int i=1;i<=h.authors_longest+interval-5;i++)printf(" ");
    printf("year");
    for(int i=1;i<=interval;i++)printf(" ");
    printf("copies\n");

    while(p) 
    { 
        int tl=strlen(p->title);
        int al=strlen(p->authors);

        printf("%d",p->id);//这里只考虑了id小于10--
        for(int i=1;i<=interval+1;i++)printf(" ");
        printf("%s",p->title);
        for(int i=1;i<=h.title_longest+interval-tl;i++)printf(" ");
        printf("%s",p->authors);
        for(int i=1;i<=h.authors_longest+interval-tl;i++)printf(" ");
        printf("%d",p->year);
        for(int i=1;i<=interval;i++)printf(" ");
        printf("%d\n",p->copies);

        p=p->next; 
    }
} 

int main(){

    
    //char *title;
    //title=(char*)malloc(sizeof(char)*6);
    //scanf("%s",title);
    //int l=strlen(title);
    //printf("%s %d\n",title,l);
    //scanf("%s",title);
    //l=strlen(title);
    //printf("%s %d\n",title,l);
    //free((void *)title); 

    char* bookFile="book.txt";
    
    BookList *all_book = (BookList *)malloc( sizeof(BookList) );
    
    FILE *fp = NULL;
    fp = fopen(bookFile, "r");
    
    if(fp==NULL)
    {
    // use the error message and exit the program if it does not
    printf("Error\nBook file does not exist: %s\n",bookFile);
    exit(0);
    }
    else
    {
    // open it if it exists
    printf("2\n");
    // use the readBooks function to read in the file and add the book records into the bookList array
    load_books(fp, all_book);
    printf("3\n");
    // remember to close the file
    fclose(fp);
    // Initialise the User data
    }
    printbook(*all_book);
    return 0;
}